### ISSUE TITLE
Loading pretrained models to be used for another project gives error: ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by luciabouzaheguerte** [basp-group/PnP-MMO-imaging#1]
Good morning. When trying to use any of the pretrained models I get the error: **ModuleNotFoundError: No module named 'models'.**

As I investigated, the problem is because of the way the model was saved. When loaded it requires the same structure and imports as when it was saved. To fix it, it is necessary that when training, only the **state_dict()** is saved.
I clarify that in my project I do not have the same structure, because I only want to use the pretrained model for another problem.

Source: https://discuss.pytorch.org/t/pytorch-load-error-no-module-named-model/25821

Thank you in advance,
Lucía

**Comment by matthieutrs** [comment]
Hello,

Before going any further: I strongly encourage you to have a look at our very recently updated training codes available [here](https://github.com/matthieutrs/LMMO_lightning), with easier training and better performing networks. The loading is simpler (see the associated [colab notebook](https://colab.research.google.com/drive/1pVNl4VhDLaYMC7KOyL8f7Zyv-zygM4vK#scrollTo=QlNANCmQkbUu)).

Back to your issue, it is true that such saving / loading approach is now strongly discouraged. In order to solve your problem, there are two options.

### 1. Loading the `state_dict` provided
Following your question, I have uploaded the associated `state_dict` in the [drive folder](https://drive.google.com/drive/folders/1jNdx8NjqYueptsfjt5X_A_WJGUacJYX5). Let me know if you have difficulties accessing it. 

The weights can be then loaded as usually:
```
import torch

# Downloading the state_dict
model_state_dict = torch.load('pth/to/state_dict.pth', map_location=lambda storage, loc: storage)

# Uploading it in your model
model = simple_CNN(n_ch_in=1, n_ch_out=1, n_ch=64, nl_type='relu', depth=20, bn=False)  # Define the model (you need to import it simple_CNN() first)
model.load_state_dict(model_state_dict, strict=True)  # Upload the weights in it
```

### 2. Recovering the `state_dict` from the model weights
Technically, it is possible to load the current model weights and extract the `state_dict`. In a temporary repository (or simply in a clone of this repository), open a jupyter notebook and do:
```
import torch
import torch.nn as nn

from models.basic_models import simple_CNN  # Necessary!

name_file = 'DnCNN_nobn_nch_3_nlev_0.007'
model_weights = torch.load('pth/to/ckpt/'+name_file+'.pth', map_location=lambda storage, loc: storage)
# print(model_weights.module.state_dict())  # If you want to print the state_dict()
```

You can then save the state_dict directly as:
```
torch.save(model_weights.module.state_dict(), 'pth/to/ckpt/'+name_file+'_dict.pth')
``` 

You can then use this `state_dict` in another repository, just as what is done in point **1.** hereabove.

I hope this helps.

Kind regards,

Matthieu

**Comment by luciabouzaheguerte** [comment]
Thank you Matthieu!
It works perfect now. I used the option 1. 

Best regards,
Lucía
